apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: k8s-training-prod

bases:
- ../../base

patchesStrategicMerge:
- deployment.yaml
- hpa.yaml

images:
- name: nginx
  newTag: "1.23"
